# Permalinks
permalink:        pretty

exclude: ['src', 'scripts', 'assets', 'node_modules', 'bower_components', 'coverage','examples']
baseurl: '/flexcss'
flexcssVersion: 'v0.3.7'
downloadLink: 'https://github.com/BowlingX/flexcss/archive/v.0.3.7.zip'